config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :users, only:[:index,:show,:edit,:update,:create] do
    resource :relationships, only:[:create,:destroy]
    get :followings, on: :member  # users直下の[:id(PK)]が付与される
    get :followers, on: :member   # users直下の[:id(PK)]が付与される
  end

  resources :books do  #ネストが好ましい
    resource :favorites, only: [:create,:destroy]
       #単数形にすると[/:id]のルートは生成されない（いいねにshowページ等不要の為）
    resources :book_comments, only: [:create,:destroy]
       #複数あるコメントの内、どのコメントを削除するかのコメント[/:id]が必要なので、複数形
  end

  get '/search' => 'searches#search'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  
  has_many :relationships, foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?  #(user.id)が(user)にフォローされているかどうか判定
  end


  attachment :profile_image  #プロフィール画像投稿をできるようにする

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,only:[:edit,:update]
  
  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
       redirect_to book_path(@book.id)
    else
       @books = Book.all
       @user = User.find(current_user.id)
       render 'books_path'
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books   # 1:Nの関係。ユーザーに紐づくbooksモデルにある本全部
    @book_new = Book.new
  end
  
  def followings  #フォロー一覧
    user = User.find(params[:id])
    @users = user.followings
  end
  
  def followers  #フォロワー一覧
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      # 更新出来ない場合の処理（エラーメッセージを表示させるため）
      render :edit 
    end
  end


private

  def book_params
    params.require(:book).permit(:title,:body)
  end
  
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userfollow.html.erb
<!--フォロー・フォロワー一覧 部分テンプレート-->

<div class="row">

  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th></th>
        <th colspan="3"></th>  <!--Show部分-->
      </tr>
    </thead>

    <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:"no_image.jpg", size:'40x40' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to "Show",user_path(user.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

 </div>

app/views/users/_userindex.html.erb
<!--ユーザー一覧 部分テンプレート-->

<table class="table">

  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>  <!--Show部分-->
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:"no_image.jpg", size:'40x40' %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.followings.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <td>
        <% if user != current_user %>
          <% if user.is_followed_by?(current_user) %>
            <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user), method: :post %>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to "Show",user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>

</table>

app/views/users/_userinfo.html.erb
<!--User info 部分テンプレート-->

<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg" %>

<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, followings_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
</table>

<div class="row">
  <% if user == current_user %>
    <%= link_to "",edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog glyphicon glyphicon-cog" %>

  <% else %>
    <% if user.is_followed_by?(current_user) %>
      <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class:"btn btn-primary" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user), method: :post, class:"btn btn-success" %>
    <% end %>

  <% end %>
</div>

app/views/users/edit.html.erb
<br>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<br>

  <h2>User info</h2>

<!--バリデーションメッセージ-->
<div id="error_explanation">
<% if @user.errors.any? %>
 <h3><%= @user.errors.count %> errors prohibited this obj from being saved: </h3>
  <ul>
     <% @user.errors.full_messages.each do |message| %>
    <li>
     <%= message %>
    </li>
     <% end %>
  </ul>
<% end %>
</div>



  <%= form_with model:@user,local: true do |f| %>

    <div class="form-group">
      <label for="user_name">Name</label><br>
      <%= f.text_field :name ,class:"form-control" %>
    </div>

    <div class="form-group">
      <label for="user_image">Image</label><br>
      <%= f.attachment_field :profile_image %>
    </div>

    <div class="form-group">
      <label for="user_introduction">Introduction</label><br>
      <%= f.text_area :introduction ,class:"form-control"%>
    </div>

    <div class="form-group">
      <%= f.submit "Update User", class:"btn btn-secondary" %>
    </div>

  <% end %>

</div>
</div>
</div>

app/views/users/followers.html.erb
<br>
<div class="container">

  <h2>Follower Users</h2>

  <% if @users.exists? %>
    <%= render 'userfollow', users: @users %>  <!--フォロー・フォロワー一覧 部分テンプレート-->
  <% else %>
    <p>ユーザーはいません</p>
  <% end %>

</div>

app/views/users/followings.html.erb
<br>
<div class="container">

<h2>Follow Users</h2>

  <% if @users.exists? %>
    <%= render 'userfollow', users: @users %>  <!--フォロー・フォロワー一覧 部分テンプレート-->
  <% else %>
    <p>ユーザーはいません</p>
  <% end %>

</div>

app/views/users/index.html.erb
<!--バリデーションチェック-->
<br>

<div class="container px-5 px-sm-0">
<div class="row">

<!-- サイドバー -->
 <div class="col-md-3">
  <%= render 'users/userinfo',user: @user %>  <!--User info 部分テンプレート-->
  <%= render 'books/newbook',book: @book %>  <!--New book 部分テンプレート-->
 </div>


<!--ユーザー 一覧-->
 <div  class="col-md-8 offset-md-1">
 <h2>Users</h2>

 <%= render 'userindex', users: @users %>  <!--ユーザー一覧 部分テンプレート-->

 </div>

</div>
</div>

app/views/users/show.html.erb
<!--処理成功メッセージ-->
<p id="notice">
  <%= notice %>
</p>


<br>
<div class="container px-5 px-sm-0">
<div class="row">
    
<!-- サイドバー -->
   <div  class="col-md-3">
   <%= render 'users/userinfo',user: @user %>  <!--User info 部分テンプレート-->
   <%= render 'books/newbook',book: @book_new %>  <!--New book 部分テンプレート-->
   </div>
  
  
<!--ログインユーザーの個人投稿一覧-->
   <div class="col-md-8 offset-md-1">
   <h2>Books</h2>

    <table class="table table-hover table-inverse">
      
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
     </tr>
    </thead>
  
    <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user,:profile_image %>
        <% end %>
      </td>
      <td>
        <%= link_to book.title, book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>
        
    <% end %>
    </tr>
    </tbody>
  
   </table>
   </div>

</div>
</div>