config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :users, only:[:index,:show,:edit,:update,:create] do
    resource :relationships, only:[:create,:destroy]
    get :followings, on: :member  # users直下の[:id(PK)]が付与される
    get :followers, on: :member   # users直下の[:id(PK)]が付与される
  end

  resources :books do  #ネストが好ましい
    resource :favorites, only: [:create,:destroy]
       #単数形にすると[/:id]のルートは生成されない（いいねにshowページ等不要の為）
    resources :book_comments, only: [:create,:destroy]
       #複数あるコメントの内、どのコメントを削除するかのコメント[/:id]が必要なので、複数形
  end

  get '/search' => 'searches#search'


end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
    #メソッドの様な使い方が出来る　例：@book.user
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?   #Favoritesテーブルの[user_id]カラムに、既に[user.id]が存在するかどうか判定
  end
  
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  

  def create
  
    @book = Book.new(book_params)
    @book.user_id = current_user.id  #ログインユーザーのidを紐付ける(@book.user_idは1:Nの関係)
    if @book.save
       redirect_to book_path(@book), notice:"You have created book successfully."
    else
      # 投稿出来ない場合の処理（エラーメッセージを表示させるため）
       @books = Book.all
       @user = User.find(current_user.id)
       render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user  # 1:Nの関係にあるもので記述可
    @book_new = Book.new  # @bookだと新規投稿フォームに既存投稿が反映されてしまう為
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
       render :edit
    else
       redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id  #ログインユーザーのidを紐付ける(@book.user_idは1:Nの関係)
    if @book.update(book_params)
       redirect_to book_path(@book), notice:"You have updated book successfully."
    else
       render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


private

  def book_params
    params.require(:book).permit(:title,:body)
  end
  

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_bookcomment.html.erb
<!--コメント機能　部分テンプレート-->

<!--コメント機能(一覧)-->
<table>
<% book.book_comments.each do |book_comment| %>
 <tr>
  <td>
   <%= link_to user_path(book_comment.user) do %>
     <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg",size:'40x40' %><br>
     <%= book_comment.user.name %>
   <% end %>
  </td>
  <td>
   <%= book_comment.comment %>
  </td>
  <td>
   <% if book_comment.user == current_user %>
   <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn-sm btn-danger" %>
   <% end %>
  </td>
 </tr>
<% end %>
</table>

<!--コメント機能(投稿)-->
<div>
  <%= form_with(model:[book,book_comment],local: true) do |f| %>
    <%= f.text_area :comment, rows:'5', cols:"80"%><br>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/books/_bookindex.html.erb
<!--投稿一覧 部分テンプレート-->

<table class="table">

  <thead>
    <tr>
      <th><!--Profile_Image--></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"><!--いいね/コメント/余白--></th>
    </tr>
  </thead>

  <tbody>
  <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id) do %>
         <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg",size:'40x40' %>
        <% end %>
      </td>
      <td>
        <%= link_to book.title,book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>

      <!--いいね機能-->
      <td id="index_favorite_<%= book.id %>">
        <%= render 'favorites/favorite', book: book %>  <!--いいね機能の部分テンプレート-->
      </td>

      <!--コメント機能-->
      <td>
        コメント数: <%= book.book_comments.count %>
      </td>


    </tr>
  <% end %>
  </tbody>

</table>

app/views/books/_newbook.html.erb
<!--部分テンプレート-->

<h2 class="mt-3">New book</h2>
   <%= form_with model:book,local: true do |f| %>
   
   <div class="form-group">
     <label for="book_title">Title</label><br>
     <%= f.text_field :title %>
   </div>
   
   <div class="form-group">
     <label for="book_opinion">Opinion</label><br>
     <%= f.text_area :body %>
   </div>
   
   <div class="form-group">
     <%= f.submit "Create Book", class:"btn btn-success col-xs-12" %>
   </div>
   <% end %>

app/views/books/edit.html.erb
<br>
<div class="container">
 
 <!--バリデーションメッセージ-->
<div id="error_explanation">
<% if @book.errors.any? %>
 <h3><%= @book.errors.count %> errors prohibited this obj from being saved: </h3>
  <ul>
     <% @book.errors.full_messages.each do |message| %>
    <li>
     <%= message %>
    </li>
     <% end %>
  </ul>
<% end %>
</div>
 
 
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">



<h2>Editing Book</h2>

<%= form_with model:@book,local: true do |f| %>

 <div class="form-group">
   <label for="book_title">Title</label><br>
   <%= f.text_field :title ,class:"form-control" %>
 </div>
 
 <div class="form-group">
   <label for="book_opinion">Opinion</label><br>
   <%= f.text_area :body ,class:"form-control" %>
 </div>
 
 <div class="form-group">
   <%= f.submit "Update Book" ,class:"btn btn-success" %>
 </div>

<% end %>

<%= link_to "Show",book_path(@book) %>
<%= " | " %>
<%= link_to "Back",books_path %>

</div>
</div>
</div>

app/views/books/index.html.erb
<br>
<div class="container px-5 px-sm-0">

<!--バリデーションメッセージ-->
<div id="error_explanation">
<% if @book.errors.any? %>
 <h3><%= @book.errors.count %> errors prohibited this obj from being saved: </h3>
  <ul>
     <% @book.errors.full_messages.each do |message| %>
    <li>
     <%= message %>
    </li>
     <% end %>
  </ul>
<% end %>
</div>

<div class="row">

<!-- サイドバー -->
<div class="col-md-3">
  <%= render 'users/userinfo',user: @user %>  <!--User info 部分テンプレート-->
  <%= render 'books/newbook',book: @book %>  <!--New book 部分テンプレート-->
</div>


<!--投稿一覧-->
<div  class="col-md-8 offset-md-1">
<h2>Books</h2>

<%= render 'bookindex', books: @books %>  <!--投稿一覧 部分テンプレート-->

</div>

</div>
</div>

app/views/books/show.html.erb
<!--処理成功メッセージ-->
<p id="notice">
  <%= notice %>
</p>

<div class="container px-5 px-sm-0">
<div class="row">

<!-- サイドバー -->
<div class="col-md-3">
  <%= render 'users/userinfo',user: @user %>  <!--User info 部分テンプレート-->
  <%= render 'books/newbook',book: @book_new %>  <!--New book 部分テンプレート-->
</div>


<!--ブック詳細-->
<div  class="col-md-8 offset-md-1">
<h2>Book detail</h2>

<table class="table table-hover table-invirse">
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(@user) do %>
         <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg",size:'40x40' %><br>
         <%= @user.name %>
        <% end %>
      </td>

      <td>
        <%= link_to @book.title, book_path(@book) %>
      </td>

      <td>
        <%= @book.body %>
      </td>

      <!--いいね機能-->
      <td id="show_favorite_<%= @book.id %>">
        <%= render 'favorites/favorite', book: @book %>  <!--いいね機能の部分テンプレート-->
      </td>

      <!--コメント機能(表示)-->
      <td id="comment_count_<%= @book.id %>">
        <%= render 'book_comments/comment_count', book: @book %>  <!--コメント数　部分テンプレート)-->
      </td>

      <!--投稿編集ボタン-->
      <td>
        <% if @user == current_user %>
        <%= link_to "Edit",edit_book_path(@book) ,class:"btn btn-success"%>
        <% end %>
      </td>

      <!--投稿削除ボタン-->
      <td>
        <% if @user == current_user %>
          <%= link_to "Destroy",book_path(@book), method: :delete ,class:"btn btn-danger", "data-confirm"=>"本当に消しますか？" %>
        <% end %>
      </td>

    </tr>
  </tbody>
</table>

<!--コメント一覧-->
<table id="comment_index_<%= @book.id %>">
  <%= render 'book_comments/comment_index', book: @book, book_comment: @book_comment %>  <!--コメント一覧　部分テンプレート-->
</table>

<!--コメント投稿-->
<div>
  <%= form_with(model:[@book,@book_comment], remote: true) do |f| %>
    <%= f.text_area :comment, rows:'5', cols:"80"%><br>
    <%= f.submit "送信" %>
  <% end %>
</div>


</div>

</div>
</div>