config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :users, only:[:index,:show,:edit,:update,:create] do
    resource :relationships, only:[:create,:destroy]
    get :followings, on: :member  # users直下の[:id(PK)]が付与される
    get :followers, on: :member   # users直下の[:id(PK)]が付与される
  end

  resources :books do  #ネストが好ましい
    resource :favorites, only: [:create,:destroy]
       #単数形にすると[/:id]のルートは生成されない（いいねにshowページ等不要の為）
    resources :book_comments, only: [:create,:destroy]
       #複数あるコメントの内、どのコメントを削除するかのコメント[/:id]が必要なので、複数形
  end

  get '/search' => 'searches#search'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
    #メソッドの様な使い方が出来る　例：@book.user
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?   #Favoritesテーブルの[user_id]カラムに、既に[user.id]が存在するかどうか判定
  end
  
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  
  has_many :relationships, foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?  #(user.id)が(user)にフォローされているかどうか判定
  end


  attachment :profile_image  #プロフィール画像投稿をできるようにする

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top,:about]   #未ログインの場合、URL直打ちしてもログイン画面へ
  
  def after_sign_in_path_for(resource)  #ログイン後にマイページへ移動
    user_path(resource)
  end
  
  def after_sign_out_path_for(resouce)  #ログアウト後にトップページへ移動
    root_path
  end


  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  

  def create
  
    @book = Book.new(book_params)
    @book.user_id = current_user.id  #ログインユーザーのidを紐付ける(@book.user_idは1:Nの関係)
    if @book.save
       redirect_to book_path(@book), notice:"You have created book successfully."
    else
      # 投稿出来ない場合の処理（エラーメッセージを表示させるため）
       @books = Book.all
       @user = User.find(current_user.id)
       render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user  # 1:Nの関係にあるもので記述可
    @book_new = Book.new  # @bookだと新規投稿フォームに既存投稿が反映されてしまう為
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
       render :edit
    else
       redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id  #ログインユーザーのidを紐付ける(@book.user_idは1:Nの関係)
    if @book.update(book_params)
       redirect_to book_path(@book), notice:"You have updated book successfully."
    else
       render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


private

  def book_params
    params.require(:book).permit(:title,:body)
  end
  

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)  #上記2行は favorite = current_user.favorites.new(book_id: book.id) に省略可
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)  #上記2行は favorite = current_user.favorites.find_by(book_id: book.id)　に省略可
    favorite.destroy
  end
  
    # redirect_to request.referer は非同期通信の為削除する
    # render先は自動的に favorites/create(destroy).js.erb となる（コントローラー名/アクション名.js.erb）

  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @model = params["search"]["model"]
    @method = params["search"]["method"]
    @content = params["search"]["content"]
    @records = search_for(@model, @method, @content)
  end


private

  def search_for(model, method, content)

    if model == 'user'
      if method == 'perfect_match'    #完全一致
        User.where(name: content)
      elsif method == 'forward_match'     #前方一致
        User.where("name LIKE ?", content+'%' )
      elsif method == 'backward_match'    #後方一致
        User.where("name LIKE ?", '%'+content )
      elsif method == 'partial_match'     #部分一致
        User.where("name LIKE ?", '%'+content+'%' )
      end

    else # model == 'book'
      if method == 'perfect_match'    #完全一致
        Book.where(title: content)
      elsif method == 'forward_match'     #前方一致
        Book.where("title LIKE ?", content+'%' )
      elsif method == 'backward_match'    #後方一致
        Book.where("title LIKE ?", '%'+content )
      elsif method == 'partial_match'     #部分一致
        Book.where("title LIKE ?", '%'+content+'%' )
      end
    end

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,only:[:edit,:update]
  
  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
       redirect_to book_path(@book.id)
    else
       @books = Book.all
       @user = User.find(current_user.id)
       render 'books_path'
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books   # 1:Nの関係。ユーザーに紐づくbooksモデルにある本全部
    @book_new = Book.new
  end
  
  def followings  #フォロー一覧
    user = User.find(params[:id])
    @users = user.followings
  end
  
  def followers  #フォロワー一覧
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      # 更新出来ない場合の処理（エラーメッセージを表示させるため）
      render :edit 
    end
  end


private

  def book_params
    params.require(:book).permit(:title,:body)
  end
  
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <!--アプリケーション全体のヘッダー-->
  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <a class="navbar-brand" href="/" >
        <span><strong>Bookers</strong></span>
       </a>

       <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">

         <li>
           <span class="glyphicon glyphicon-home"></span>
           <%= link_to" Home", user_path(current_user), class:"fas fa-home nav-link text-light" %>
         </li>

         <li>
           <span class="glyphicon glyphicon-user"></span>
           <%= link_to" Users", users_path, class:"fas fa-users nav-link text-light" %>
         </li>

         <li>
           <span class="glyphicon glyphicon-book"></span>
           <%= link_to" Books", books_path, class:"fas fa-book-open nav-link text-light" %>
         </li>

         <li>
           <span class="glyphicon glyphicon-log-out"></span>
           <%= link_to" logout", destroy_user_session_path,method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %>
         </li>

        </ul>

       <% else %>
        <ul class="navbar-nav ml-auto">
         <li>
           <span class="glyphicon glyphicon-home"></span>
           <%= link_to" Home", root_path, class:"fas fa-home nav-link text-light" %>
         </li>

         <li>
           <span class="glyphicon glyphicon-link"></span>
           <%= link_to" About", home_about_path, class:"fas fa-link nav-link text-light" %>
         </li>


         <li>
           <span class="glyphicon glyphicon-edit"></span>
           <%= link_to" sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
         </li>

         <li>
           <span class="glyphicon glyphicon-log-in"></span>
           <%= link_to" login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
         </li>

        </ul>
       <% end %>
       </div>

      </div>
    </nav>


    <!--検索フォーム-->
    <div class ='search'>
      <%= render 'searches/form' %>
    </div>


  </header>


  <!--各html.erbを読み込む-->
  <main>
    <%= yield %>
  </main>


  <!--アプリケーション全体のフッター-->
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>

  </body>
</html>